version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - pip install -r trending/requirements.txt
      - pip install pylint
  build:
    commands:
      - python setup.py test
      - pylint -E src
artifacts:
  files:
    - '**/*'
  base-directory: trending
